### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by uanLy** [SeetaFace6Sharp/SeetaFace6Sharp#1]
**相关代码**
            using var bmp = (Bitmap)Image.FromFile(@"C:\Users\PC\Desktop\face.jpg");
            using var faceImg = bmp.ToFaceImage();
            using var detector = new FaceDetector(); /*此行报错*/
            FaceInfo[] infos = detector.Detect(faceImg);
            Console.WriteLine($"识别到 {infos.Length} 个人脸信息：\n");
            Console.WriteLine($"No.\t人脸置信度\t位置信息");
            for (int i = 0; i < infos.Length; i++)
            {
                Console.WriteLine($"{i}\t{infos[i].Score:f8}\t{infos[i].Location}");
            }

**异常信息**
System.Runtime.InteropServices.SEHException:“External component has thrown an exception.”

**开发环境**
 - 目标框架: [e.g. .net6]
 - 项目类型 [e.g. Windows窗体应用]

**相关包清单**
 - [e.g. SeetaFace6Sharp 1.0.1]
 - [e.g. SeetaFace6Sharp.model.face_recognizer_mask 1.0.0]
 - [e.g. SeetaFace6Sharp.Extension.SystemDrawing 1.0.1]
 - [e.g. SeetaFace6Sharp.runtime.win.x64 1.0.1]
 - [e.g. SeetaFace6Sharp.runtime.win.x86 1.0.1]

**运行环境**
 - 操作系统: [e.g. Windows 10 家庭中文版]
 - 系统类型: [e.g. 64 位操作系统, 基于 x64 的处理器]
 - 处理器: [e.g. Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz]

**附件**

**Comment by withsalt** [comment]
什么操作系统哇？

**Comment by uanLy** [comment]
windows家庭版，运行环境写了

**Comment by uanLy** [comment]
> 什么操作系统哇？

window10 家庭版，issue有描述

**Comment by withsalt** [comment]
Windows 系统需要安装Visual C++ 14，安装了吗？

**Comment by uanLy** [comment]
> Windows 系统需要安装Visual C++ 14，安装了吗？

如图(https://user-images.githubusercontent.com/46877701/228417454-1b111885-4110-4435-974c-9c12abcceb81.png)

**Comment by withsalt** [comment]
非常感谢反馈！方便的话，能加我一个Q吗？770702827，我这边没法复现出来。

**Comment by uanLy** [comment]
QQ已加，我代码发你，你看看



青木匣
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SeetaFace6Sharp/SeetaFace6Sharp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SeetaFace6Sharp/SeetaFace6Sharp] [Bug] (Issue #1)





 
非常感谢反馈！方便的话，能加我一个Q吗？770702827，我这边没法复现出来。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

playground.zip (102.50M, 2023年04月28日 15:02 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=76383864d4c7a2cd0a45a63a1f37071b4d4c015d0e520556185959545c1a5450000115500a560319070e08565f04515557595b0139393544595941034b58405a5116420d493708&code=588d9754

**Comment by uanLy** [comment]
模型包错误，将 SeetaFace6Sharp.model.face_recognizer_mask 1.0.0
改为
SeetaFace6Sharp.model.face_detector
