### ISSUE TITLE
这两天在项目中使用到了，功能没问题，就是比对出来的相似度变化范围不大

### ISSUE THREAD

**Issue by huaxuanHan** [SeetaFace6Sharp/SeetaFace6Sharp#3]
这两天在项目中使用到了，功能没问题，就是比对出来的相似度变化范围不大，我们是用在景区门口，两个摄像头抓拍人脸，图片汇总到服务器上面的FTP,我从文件夹里读图片跟底库比较，比对相似度基本都是40%以上，一般是50%，这是没比中底库的相似度，我们自己人测试了一下，相似度也就是65%，这个阈值的话就不好设置了，因为每天的人流量比较大，一天5万以上吧，阈值设置的低了误报频繁，设置的高了又比不出，这个有啥办法能提高准确度吗?

**Comment by withsalt** [comment]
尝试使用1024特征长度。

主要是阈值太低了，我建议优化方向是使用更清晰的图片，提高阈值。
