### ISSUE TITLE
1比120000需要30秒，这个怎么能提高一下速度呢

### ISSUE THREAD

**Issue by huaxuanHan** [SeetaFace6Sharp/SeetaFace6Sharp#4]
1比120000需要30秒，这个怎么能提高一下速度呢，
在我电脑上用light模型两张图片的相似度是70%，nomal模型相似度是90%，在服务器上的light模型相似度就是80%，我觉得应该是跟我电脑上一样70%啊，这是咋回事？为了提高速度，我加了质量评估，质量差的就不比了，但是质量评估的效果也不好，人脸完整度和遮挡这两个感觉结果不是很准确

**Comment by withsalt** [comment]
提高速度建议：
1、可以使用GPU，SeetaFace6本身使用CPU计算速度就不是很理想。
2、使用OpenVINO等比较活跃的深度学习框架，SeetaFace6很久没更新了。（OpenVINO这玩意儿人脸特征值检测速度可以把SeetaFace6吊起来锤）

_在我电脑上用light模型两张图片的相似度是70%，nomal模型相似度是90%，在服务器上的light模型相似度就是80%_
在本地和服务器上面，是同样的图像吗？

**Comment by huaxuanHan** [comment]
同样的两张图像，在不同的电脑上相似度不一样

**Comment by huaxuanHan** [comment]
设置成GPU的话报错

**Comment by huaxuanHan** [comment]
![微信截图_20240220105229](https://github.com/SeetaFace6Sharp/SeetaFace6Sharp/assets/60837230/0507d6b9-707e-4480-a5dc-ba9b323b68c1)

**Comment by withsalt** [comment]
> 同样的两张图像，在不同的电脑上相似度不一样

方便提供图像进行测试吗？sysrun@163.com

**Comment by withsalt** [comment]
> 设置成GPU的话报错

GPU使用说明：https://github.com/SeetaFace6Sharp/SeetaFace6Sharp/blob/main/docs/SeetaFace6SharpAPI.md#%E4%BD%BF%E7%94%A8gpu

**Comment by huaxuanHan** [comment]
GPU报错的问题解决了，我测试一下速度确实快了2倍，图片已发
