### ISSUE TITLE
[Bug]长时间运行会报错,内存溢出

### ISSUE THREAD

**Issue by dcx013** [SeetaFace6Sharp/SeetaFace6Sharp#6]
**简明描述**
External component has thrown an exception.   
at SeetaFace6Sharp.Native.SeetaFace6Native.FaceDetectV2(IntPtr handler, FaceImage& img, Int32 maxFaceCount, IntPtr buffer, Int32& size)
**重现步骤**

**开发环境**
 - 目标框架: [.net8 win10win7
 - 项目类型 wpf

**相关包清单**

![image](https://github.com/SeetaFace6Sharp/SeetaFace6Sharp/assets/15107161/d7f95ef7-fbff-4f50-8ae3-01025537924b)

**运行环境**
 - 操作系统: win10 win7
 - 系统类型: 64 位操作系统
 - 处理器: i5 9400f

**附件**

**Comment by withsalt** [comment]
能否把调用代码贴出来一下呢？

**Comment by dcx013** [comment]
> 能否把调用代码贴出来一下呢？

由于FaceDetectV2报错,导致faceimage没有释放,内存溢出,问题解决了
